create schema if not exists meitra_private;

create table if not exists meitra_private.seat_identity_migration_audit (
  id bigint generated by default as identity primary key,
  migration_version text not null,
  entity_name text not null,
  unresolved_count bigint not null,
  details jsonb not null default '{}'::jsonb,
  recorded_at timestamptz not null default now()
);

revoke all on table meitra_private.seat_identity_migration_audit
  from public, anon, authenticated;
grant select on table meitra_private.seat_identity_migration_audit
  to service_role;

alter table public.rooms
  add column if not exists host_seat_id uuid;

alter table public.game_states
  add column if not exists current_seat_id uuid;

alter table public.game_history
  add column if not exists actor_seat_id uuid,
  add column if not exists actor_key_snapshot text;

alter table public.active_room_memberships
  add column if not exists seat_id uuid;

alter table public.room_membership_events
  add column if not exists seat_id uuid;

alter table public.room_players
  drop constraint if exists room_players_user_id_fkey;

alter table public.room_players
  add constraint room_players_user_id_fkey
  foreign key (user_id)
  references public.user_profiles(id)
  on delete set null;

alter table public.room_players
  add constraint room_players_room_id_id_key unique (room_id, id);

create unique index if not exists room_players_room_user_unique
  on public.room_players(room_id, user_id)
  where user_id is not null;

create index if not exists rooms_host_seat_id_idx
  on public.rooms(host_seat_id);

create index if not exists game_states_current_seat_id_idx
  on public.game_states(current_seat_id)
  where current_seat_id is not null;

create index if not exists game_history_actor_seat_id_idx
  on public.game_history(actor_seat_id)
  where actor_seat_id is not null;

create index if not exists active_room_memberships_room_seat_idx
  on public.active_room_memberships(room_id, seat_id)
  where room_id is not null;

create index if not exists room_membership_events_seat_created_idx
  on public.room_membership_events(seat_id, created_at desc)
  where seat_id is not null;

create or replace function meitra_private.resolve_room_seat_id(
  p_room_id uuid,
  p_identity_key text default null,
  p_user_id uuid default null
)
returns uuid
language sql
stable
security definer
set search_path = ''
as $function$
  select room_player.id
  from public.room_players as room_player
  where room_player.room_id = p_room_id
    and (
      (p_identity_key is not null and room_player.id::text = p_identity_key)
      or (
        p_identity_key is not null
        and room_player.player_id = p_identity_key
      )
      or (p_user_id is not null and room_player.user_id = p_user_id)
    )
  order by case
    when p_identity_key is not null
      and room_player.id::text = p_identity_key then 0
    when p_identity_key is not null
      and room_player.player_id = p_identity_key then 1
    else 2
  end
  limit 1;
$function$;

revoke all on function meitra_private.resolve_room_seat_id(uuid, text, uuid)
  from public, anon, authenticated;
grant execute on function meitra_private.resolve_room_seat_id(uuid, text, uuid)
  to service_role;

update public.rooms as room
set host_seat_id = meitra_private.resolve_room_seat_id(
  room.id,
  room.host_id,
  case
    when room.host_id ~* '^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$'
      then room.host_id::uuid
    else null
  end
)
where room.host_seat_id is null;

update public.game_states as game_state
set current_seat_id = meitra_private.resolve_room_seat_id(
  game_state.room_id,
  game_state.current_player_id,
  null
)
where game_state.current_seat_id is null
  and game_state.current_player_id is not null;

update public.game_history as history
set
  actor_key_snapshot = coalesce(history.actor_key_snapshot, history.player_id),
  actor_seat_id = coalesce(
    history.actor_seat_id,
    meitra_private.resolve_room_seat_id(
      history.room_id,
      history.player_id,
      null
    )
  )
where history.player_id is not null
   or history.actor_key_snapshot is not null;

update public.active_room_memberships as membership
set seat_id = meitra_private.resolve_room_seat_id(
  membership.room_id,
  membership.player_id,
  membership.user_id
)
where membership.room_id is not null
  and membership.seat_id is null;

update public.room_membership_events as event
set seat_id = meitra_private.resolve_room_seat_id(
  coalesce(event.to_room_id, event.from_room_id),
  null,
  event.user_id
)
where event.seat_id is null
  and coalesce(event.to_room_id, event.from_room_id) is not null;

update public.game_states
set state_data = jsonb_set(
  coalesce(state_data, '{}'::jsonb),
  '{identitySchemaVersion}',
  coalesce(state_data->'identitySchemaVersion', '1'::jsonb),
  true
);

insert into meitra_private.seat_identity_migration_audit (
  migration_version,
  entity_name,
  unresolved_count,
  details
)
select
  '20260810100000',
  'rooms.host_seat_id',
  count(*),
  jsonb_build_object('legacyColumn', 'rooms.host_id')
from public.rooms
where host_id is not null
  and host_seat_id is null
union all
select
  '20260810100000',
  'game_states.current_seat_id',
  count(*),
  jsonb_build_object('legacyColumn', 'game_states.current_player_id')
from public.game_states
where current_player_id is not null
  and current_seat_id is null
union all
select
  '20260810100000',
  'game_history.actor_seat_id',
  count(*),
  jsonb_build_object('legacyColumn', 'game_history.player_id')
from public.game_history
where player_id is not null
  and actor_seat_id is null
union all
select
  '20260810100000',
  'active_room_memberships.seat_id',
  count(*),
  jsonb_build_object('legacyColumn', 'active_room_memberships.player_id')
from public.active_room_memberships
where room_id is not null
  and seat_id is null;

alter table public.rooms
  add constraint rooms_host_seat_same_room_fkey
  foreign key (id, host_seat_id)
  references public.room_players(room_id, id)
  on delete set null (host_seat_id)
  deferrable initially deferred
  not valid;

alter table public.game_states
  add constraint game_states_current_seat_same_room_fkey
  foreign key (room_id, current_seat_id)
  references public.room_players(room_id, id)
  on delete set null (current_seat_id)
  deferrable initially deferred
  not valid;

alter table public.game_history
  add constraint game_history_actor_seat_same_room_fkey
  foreign key (room_id, actor_seat_id)
  references public.room_players(room_id, id)
  on delete set null (actor_seat_id)
  deferrable initially deferred
  not valid;

alter table public.active_room_memberships
  add constraint active_room_memberships_seat_same_room_fkey
  foreign key (room_id, seat_id)
  references public.room_players(room_id, id)
  deferrable initially deferred
  not valid;

alter table public.room_membership_events
  add constraint room_membership_events_seat_fkey
  foreign key (seat_id)
  references public.room_players(id)
  on delete set null
  deferrable initially deferred
  not valid;

alter table public.rooms
  validate constraint rooms_host_seat_same_room_fkey;
alter table public.game_states
  validate constraint game_states_current_seat_same_room_fkey;
alter table public.game_history
  validate constraint game_history_actor_seat_same_room_fkey;
alter table public.active_room_memberships
  validate constraint active_room_memberships_seat_same_room_fkey;
alter table public.room_membership_events
  validate constraint room_membership_events_seat_fkey;

create or replace function public.reject_room_player_seat_id_change()
returns trigger
language plpgsql
security invoker
set search_path = public
as $function$
begin
  if new.id is distinct from old.id then
    raise exception 'room_player_seat_id_is_immutable room=% seat=%',
      old.room_id,
      old.id
      using errcode = 'PT422';
  end if;
  if new.room_id is distinct from old.room_id then
    raise exception 'room_player_room_id_is_immutable room=% seat=%',
      old.room_id,
      old.id
      using errcode = 'PT422';
  end if;
  if new.seat_index is distinct from old.seat_index then
    raise exception 'room_player_seat_index_is_immutable room=% seat=% index=%',
      old.room_id,
      old.id,
      old.seat_index
      using errcode = 'PT422';
  end if;

  return new;
end;
$function$;

drop trigger if exists reject_room_player_seat_id_change
  on public.room_players;

create trigger reject_room_player_seat_id_change
before update of id, room_id, seat_index on public.room_players
for each row execute function public.reject_room_player_seat_id_change();

create or replace function public.reject_room_player_seat_delete()
returns trigger
language plpgsql
security invoker
set search_path = public
as $function$
begin
  if exists (
    select 1
    from public.rooms
    where id = old.room_id
  ) then
    raise exception 'room_player_seat_delete_requires_room_delete room=% seat=%',
      old.room_id,
      old.id
      using errcode = 'PT422';
  end if;

  return old;
end;
$function$;

drop trigger if exists reject_room_player_seat_delete
  on public.room_players;

create trigger reject_room_player_seat_delete
before delete on public.room_players
for each row execute function public.reject_room_player_seat_delete();

comment on column public.room_players.id is
  'Canonical immutable seat UUID. Runtime seatId and legacy playerId aliases resolve to this value.';
comment on column public.room_players.player_id is
  'Legacy occupant key retained during dual-write migration. Do not use as canonical seat identity.';
comment on column public.rooms.host_seat_id is
  'Canonical host seat UUID scoped to this room.';
comment on column public.game_states.current_seat_id is
  'Canonical current-turn seat UUID scoped to this room.';
comment on column public.game_history.actor_seat_id is
  'Canonical actor seat UUID when the source row can be resolved.';
comment on column public.game_history.actor_key_snapshot is
  'Immutable legacy actor key retained for unresolved and historical records.';

select pg_notify('pgrst', 'reload schema');
