create type public.active_room_membership_status as enum (
  'moving',
  'active',
  'disconnected'
);

create table public.active_room_memberships (
  user_id uuid primary key references public.user_profiles(id) on delete cascade,
  room_id uuid references public.rooms(id) on delete cascade,
  player_id varchar(255) not null,
  status public.active_room_membership_status not null,
  membership_version bigint not null default 1,
  transition_id uuid not null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  last_seen_at timestamptz not null default now(),
  constraint active_room_memberships_version_positive
    check (membership_version > 0),
  constraint active_room_memberships_room_required
    check (status = 'moving' or room_id is not null)
);

create unique index active_room_memberships_room_player_key
  on public.active_room_memberships(room_id, player_id)
  where room_id is not null;

create index active_room_memberships_room_id_idx
  on public.active_room_memberships(room_id)
  where room_id is not null;

create trigger update_active_room_memberships_updated_at
before update on public.active_room_memberships
for each row execute function public.update_updated_at_column();

create table public.room_membership_events (
  id bigint generated by default as identity primary key,
  transition_id uuid not null,
  user_id uuid not null references public.user_profiles(id) on delete cascade,
  from_room_id uuid references public.rooms(id) on delete set null,
  to_room_id uuid references public.rooms(id) on delete set null,
  event_type text not null,
  membership_version bigint,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

create index room_membership_events_transition_idx
  on public.room_membership_events(transition_id);

create index room_membership_events_user_created_idx
  on public.room_membership_events(user_id, created_at desc);

alter table public.active_room_memberships enable row level security;
alter table public.room_membership_events enable row level security;

revoke all on table public.active_room_memberships
  from public, anon, authenticated;
revoke all on table public.room_membership_events
  from public, anon, authenticated;
revoke all on sequence public.room_membership_events_id_seq
  from public, anon, authenticated;

grant all on table public.active_room_memberships to service_role;
grant all on table public.room_membership_events to service_role;
grant usage on sequence public.room_membership_events_id_seq to service_role;

create or replace function public.reserve_room_membership(
  p_user_id uuid,
  p_player_id text,
  p_transition_id uuid
)
returns jsonb
language plpgsql
set search_path to ''
as $function$
declare
  current_membership public.active_room_memberships%rowtype;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

  select *
  into current_membership
  from public.active_room_memberships
  where user_id = p_user_id
  for update;

  if not found then
    insert into public.active_room_memberships (
      user_id,
      room_id,
      player_id,
      status,
      membership_version,
      transition_id
    ) values (
      p_user_id,
      null,
      p_player_id,
      'moving',
      1,
      p_transition_id
    )
    returning * into current_membership;

    insert into public.room_membership_events (
      transition_id,
      user_id,
      event_type,
      membership_version
    ) values (
      p_transition_id,
      p_user_id,
      'create_reserved',
      current_membership.membership_version
    );

    return jsonb_build_object(
      'result', 'reserved',
      'membership', to_jsonb(current_membership)
    );
  end if;

  if current_membership.status = 'moving'
    and current_membership.transition_id = p_transition_id then
    return jsonb_build_object(
      'result', 'reserved',
      'membership', to_jsonb(current_membership)
    );
  end if;

  if current_membership.status = 'moving'
    and current_membership.updated_at < now() - interval '2 minutes' then
    update public.active_room_memberships
    set
      player_id = p_player_id,
      membership_version = membership_version + 1,
      transition_id = p_transition_id,
      last_seen_at = now()
    where user_id = p_user_id
    returning * into current_membership;

    insert into public.room_membership_events (
      transition_id,
      user_id,
      event_type,
      membership_version,
      metadata
    ) values (
      p_transition_id,
      p_user_id,
      'create_reservation_recovered',
      current_membership.membership_version,
      jsonb_build_object('leaseSeconds', 120)
    );

    return jsonb_build_object(
      'result', 'reserved',
      'membership', to_jsonb(current_membership)
    );
  end if;

  return jsonb_build_object(
    'result', 'conflict',
    'membership', to_jsonb(current_membership)
  );
end;
$function$;

create or replace function public.claim_room_membership(
  p_user_id uuid,
  p_room_id uuid,
  p_player_id text,
  p_transition_id uuid
)
returns jsonb
language plpgsql
set search_path to ''
as $function$
declare
  current_membership public.active_room_memberships%rowtype;
  previous_room_id uuid;
  claim_result text;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

  select *
  into current_membership
  from public.active_room_memberships
  where user_id = p_user_id
  for update;

  if not found then
    insert into public.active_room_memberships (
      user_id,
      room_id,
      player_id,
      status,
      membership_version,
      transition_id,
      last_seen_at
    ) values (
      p_user_id,
      p_room_id,
      p_player_id,
      'active',
      1,
      p_transition_id,
      now()
    )
    returning * into current_membership;
    claim_result := 'claimed';
  elsif current_membership.status = 'moving'
    and current_membership.transition_id = p_transition_id then
    previous_room_id := current_membership.room_id;
    update public.active_room_memberships
    set
      room_id = p_room_id,
      player_id = p_player_id,
      status = 'active',
      membership_version = membership_version + 1,
      last_seen_at = now()
    where user_id = p_user_id
    returning * into current_membership;
    claim_result := 'claimed';
  elsif current_membership.room_id = p_room_id then
    previous_room_id := current_membership.room_id;
    update public.active_room_memberships
    set
      player_id = p_player_id,
      status = 'active',
      membership_version = membership_version + 1,
      transition_id = p_transition_id,
      last_seen_at = now()
    where user_id = p_user_id
    returning * into current_membership;
    claim_result := 'reconnected';
  else
    return jsonb_build_object(
      'result', 'conflict',
      'membership', to_jsonb(current_membership)
    );
  end if;

  insert into public.room_membership_events (
    transition_id,
    user_id,
    from_room_id,
    to_room_id,
    event_type,
    membership_version
  ) values (
    p_transition_id,
    p_user_id,
    previous_room_id,
    p_room_id,
    case
      when claim_result = 'reconnected' then 'room_reconnected'
      else 'room_claimed'
    end,
    current_membership.membership_version
  );

  return jsonb_build_object(
    'result', claim_result,
    'membership', to_jsonb(current_membership)
  );
end;
$function$;

create or replace function public.cancel_room_membership_reservation(
  p_user_id uuid,
  p_transition_id uuid
)
returns boolean
language plpgsql
set search_path to ''
as $function$
declare
  deleted_count integer;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

  delete from public.active_room_memberships
  where user_id = p_user_id
    and status = 'moving'
    and transition_id = p_transition_id;

  get diagnostics deleted_count = row_count;
  if deleted_count > 0 then
    insert into public.room_membership_events (
      transition_id,
      user_id,
      event_type
    ) values (
      p_transition_id,
      p_user_id,
      'create_reservation_cancelled'
    );
  end if;

  return deleted_count > 0;
end;
$function$;

create or replace function public.release_room_membership(
  p_user_id uuid,
  p_room_id uuid,
  p_expected_version bigint,
  p_transition_id uuid
)
returns jsonb
language plpgsql
set search_path to ''
as $function$
declare
  current_membership public.active_room_memberships%rowtype;
begin
  perform pg_advisory_xact_lock(hashtextextended(p_user_id::text, 0));

  select *
  into current_membership
  from public.active_room_memberships
  where user_id = p_user_id
  for update;

  if not found then
    return jsonb_build_object('result', 'released');
  end if;

  if current_membership.room_id is distinct from p_room_id
    or current_membership.membership_version <> p_expected_version then
    return jsonb_build_object(
      'result', 'stale',
      'membership', to_jsonb(current_membership)
    );
  end if;

  delete from public.active_room_memberships
  where user_id = p_user_id;

  insert into public.room_membership_events (
    transition_id,
    user_id,
    from_room_id,
    event_type,
    membership_version
  ) values (
    p_transition_id,
    p_user_id,
    p_room_id,
    'room_released',
    current_membership.membership_version
  );

  return jsonb_build_object('result', 'released');
end;
$function$;

create or replace function public.release_room_membership_by_player(
  p_room_id uuid,
  p_player_id text,
  p_transition_id uuid
)
returns boolean
language plpgsql
set search_path to ''
as $function$
declare
  target_user_id uuid;
  target_version bigint;
begin
  select user_id, membership_version
  into target_user_id, target_version
  from public.active_room_memberships
  where room_id = p_room_id
    and player_id = p_player_id;

  if not found then
    return false;
  end if;

  perform pg_advisory_xact_lock(hashtextextended(target_user_id::text, 0));

  delete from public.active_room_memberships
  where user_id = target_user_id
    and room_id = p_room_id
    and player_id = p_player_id;

  if not found then
    return false;
  end if;

  insert into public.room_membership_events (
    transition_id,
    user_id,
    from_room_id,
    event_type,
    membership_version
  ) values (
    p_transition_id,
    target_user_id,
    p_room_id,
    'player_membership_released',
    target_version
  );

  return true;
end;
$function$;

create or replace function public.release_room_memberships_for_room(
  p_room_id uuid,
  p_transition_id uuid
)
returns integer
language plpgsql
set search_path to ''
as $function$
declare
  released_count integer;
begin
  with deleted_memberships as (
    delete from public.active_room_memberships
    where room_id = p_room_id
    returning user_id, membership_version
  ), inserted_events as (
    insert into public.room_membership_events (
      transition_id,
      user_id,
      from_room_id,
      event_type,
      membership_version
    )
    select
      p_transition_id,
      user_id,
      p_room_id,
      'room_closed',
      membership_version
    from deleted_memberships
    returning 1
  )
  select count(*) into released_count from inserted_events;

  return released_count;
end;
$function$;

revoke all on function public.reserve_room_membership(uuid, text, uuid)
  from public, anon, authenticated;
revoke all on function public.claim_room_membership(uuid, uuid, text, uuid)
  from public, anon, authenticated;
revoke all on function public.cancel_room_membership_reservation(uuid, uuid)
  from public, anon, authenticated;
revoke all on function public.release_room_membership(uuid, uuid, bigint, uuid)
  from public, anon, authenticated;
revoke all on function public.release_room_membership_by_player(uuid, text, uuid)
  from public, anon, authenticated;
revoke all on function public.release_room_memberships_for_room(uuid, uuid)
  from public, anon, authenticated;

grant execute on function public.reserve_room_membership(uuid, text, uuid)
  to service_role;
grant execute on function public.claim_room_membership(uuid, uuid, text, uuid)
  to service_role;
grant execute on function public.cancel_room_membership_reservation(uuid, uuid)
  to service_role;
grant execute on function public.release_room_membership(uuid, uuid, bigint, uuid)
  to service_role;
grant execute on function public.release_room_membership_by_player(uuid, text, uuid)
  to service_role;
grant execute on function public.release_room_memberships_for_room(uuid, uuid)
  to service_role;

select pg_notify('pgrst', 'reload schema');
