// Generated by build-densho-cards.mjs; do not edit.
export const DENSHO_STYLED_SOURCES: Record<string, Record<'small' | 'medium' | 'large', () => number>> = {
  "10_C": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/10_C.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/10_C.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/10_C.webp'),
  },
  "10_D": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/10_D.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/10_D.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/10_D.webp'),
  },
  "10_H": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/10_H.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/10_H.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/10_H.webp'),
  },
  "10_S": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/10_S.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/10_S.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/10_S.webp'),
  },
  "2_C": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/2_C.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/2_C.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/2_C.webp'),
  },
  "2_D": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/2_D.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/2_D.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/2_D.webp'),
  },
  "2_H": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/2_H.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/2_H.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/2_H.webp'),
  },
  "2_S": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/2_S.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/2_S.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/2_S.webp'),
  },
  "3_C": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/3_C.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/3_C.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/3_C.webp'),
  },
  "3_D": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/3_D.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/3_D.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/3_D.webp'),
  },
  "3_H": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/3_H.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/3_H.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/3_H.webp'),
  },
  "3_S": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/3_S.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/3_S.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/3_S.webp'),
  },
  "4_C": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/4_C.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/4_C.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/4_C.webp'),
  },
  "4_D": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/4_D.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/4_D.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/4_D.webp'),
  },
  "4_H": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/4_H.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/4_H.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/4_H.webp'),
  },
  "4_S": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/4_S.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/4_S.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/4_S.webp'),
  },
  "5_C": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/5_C.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/5_C.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/5_C.webp'),
  },
  "5_D": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/5_D.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/5_D.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/5_D.webp'),
  },
  "5_H": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/5_H.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/5_H.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/5_H.webp'),
  },
  "5_S": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/5_S.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/5_S.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/5_S.webp'),
  },
  "6_C": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/6_C.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/6_C.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/6_C.webp'),
  },
  "6_D": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/6_D.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/6_D.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/6_D.webp'),
  },
  "6_H": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/6_H.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/6_H.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/6_H.webp'),
  },
  "6_S": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/6_S.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/6_S.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/6_S.webp'),
  },
  "7_C": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/7_C.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/7_C.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/7_C.webp'),
  },
  "7_D": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/7_D.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/7_D.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/7_D.webp'),
  },
  "7_H": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/7_H.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/7_H.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/7_H.webp'),
  },
  "7_S": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/7_S.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/7_S.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/7_S.webp'),
  },
  "8_C": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/8_C.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/8_C.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/8_C.webp'),
  },
  "8_D": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/8_D.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/8_D.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/8_D.webp'),
  },
  "8_H": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/8_H.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/8_H.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/8_H.webp'),
  },
  "8_S": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/8_S.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/8_S.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/8_S.webp'),
  },
  "9_C": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/9_C.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/9_C.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/9_C.webp'),
  },
  "9_D": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/9_D.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/9_D.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/9_D.webp'),
  },
  "9_H": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/9_H.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/9_H.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/9_H.webp'),
  },
  "9_S": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/9_S.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/9_S.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/9_S.webp'),
  },
  "A_C": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/A_C.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/A_C.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/A_C.webp'),
  },
  "A_D": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/A_D.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/A_D.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/A_D.webp'),
  },
  "A_H": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/A_H.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/A_H.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/A_H.webp'),
  },
  "A_S": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/A_S.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/A_S.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/A_S.webp'),
  },
  "J_C": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/J_C.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/J_C.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/J_C.webp'),
  },
  "J_D": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/J_D.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/J_D.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/J_D.webp'),
  },
  "J_H": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/J_H.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/J_H.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/J_H.webp'),
  },
  "J_S": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/J_S.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/J_S.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/J_S.webp'),
  },
  "K_C": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/K_C.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/K_C.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/K_C.webp'),
  },
  "K_D": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/K_D.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/K_D.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/K_D.webp'),
  },
  "K_H": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/K_H.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/K_H.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/K_H.webp'),
  },
  "K_S": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/K_S.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/K_S.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/K_S.webp'),
  },
  "Q_C": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/Q_C.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/Q_C.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/Q_C.webp'),
  },
  "Q_D": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/Q_D.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/Q_D.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/Q_D.webp'),
  },
  "Q_H": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/Q_H.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/Q_H.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/Q_H.webp'),
  },
  "Q_S": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/Q_S.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/Q_S.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/Q_S.webp'),
  },
  "card_back": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/card_back.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/card_back.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/card_back.webp'),
  },
  "joker_red": {
    small: () => require('@meitra/game-client/assets/densho/styled/small/joker_red.webp'),
    medium: () => require('@meitra/game-client/assets/densho/styled/medium/joker_red.webp'),
    large: () => require('@meitra/game-client/assets/densho/styled/joker_red.webp'),
  },
};
