name: Deploy to Fly.io

on:
  push:
    branches:
      - main  # mainブランチへのpushをトリガーに

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Fly.io CLI
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy app to Fly.io
        run: flyctl deploy --remote-only -c fly.toml
        working-directory: mei-tra-backend
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}